---
# Playbook for provisioning a bare metal host
- name: Provision bare metal host
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    host_ip: "{{ host_ip }}"
    ssh_user: "{{ ssh_user }}"
    ssh_port: "{{ ssh_port }}"

  roles:
    - role: setup_essentials

  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install system utilities
      apt:
        name:
          - htop
          - iotop
          - nmon
          - sysstat
          - dstat
          - net-tools
          - tcpdump
          - iftop
          - smartmontools
          - lvm2
          - curl
          - wget
          - vim
          - unzip
        state: present

    - name: Install security packages
      apt:
        name:
          - fail2ban
          - ufw
        state: present

    - name: Configure UFW default policy
      ufw:
        state: enabled
        policy: deny

    - name: Allow SSH connections
      ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp

    - name: Enable fail2ban for SSH
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port    = {{ ssh_port }}
          logpath = %(sshd_log)s
          maxretry = 5
          bantime = 3600

    - name: Enable system statistics collection
      service:
        name: sysstat
        state: started
        enabled: yes

    - name: Configure SSH hardening
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding yes' }
      notify: Restart SSH

    - name: Configure system optimization
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_set: yes
        reload: yes
      with_items:
        - { name: 'vm.swappiness', value: '10' }
        - { name: 'vm.dirty_ratio', value: '20' }
        - { name: 'vm.dirty_background_ratio', value: '5' }
        - { name: 'net.core.somaxconn', value: '65535' }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: '65535' }
        - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted 